### ISSUE TITLE
Error in disney material rendering

### ISSUE THREAD

**Issue by tigrazone** [yuphin/Lumen#24]
With all integrators left sphere is black
![image](https://github.com/yuphin/Lumen/assets/3808839/779e6f85-c11e-4773-bd52-407909bfe64b)

**Comment by tigrazone** [comment]
I do #define ENABLE_DISNEY 1
and all ok with disney material
![image](https://github.com/yuphin/Lumen/assets/3808839/861bb8f5-597a-4925-aa0f-3db6cb696372)
sorry

**Comment by yuphin** [comment]
Yes, this was a deliberate design choice at the time since it incurred a lot of execution divergence.
