### ISSUE TITLE
absense of GLASS material in ENABLE_DISNEY mode. and wrong SPPM after add it

### ISSUE THREAD

**Issue by tigrazone** [yuphin/Lumen#27]
I try to render torus scene in ENABLE_DISNEY mode with SPPM integrator and I see this
![image](https://github.com/yuphin/Lumen/assets/3808839/2c28b62d-cd89-406c-b7fb-48321d00f02b)

After investigation I add GLASS material and SPPM renders this
![image](https://github.com/yuphin/Lumen/assets/3808839/c654ddd6-8450-4bf6-b86d-cfc7df183c94)

fixed with https://github.com/tigrazone/Lumen/commit/bb23059cbb4311e4277be0fca2f28ca953ecdf95

I just change <integrator type="vcm"> to <integrator type="sppm"> in torus.xml scene file
with VCM renders ok
![image](https://github.com/yuphin/Lumen/assets/3808839/ffe10f6a-154d-4ed3-b834-68409c6676de)

SPPM integrator with ENABLE_DISNEY 0 mode gives me
![image](https://github.com/yuphin/Lumen/assets/3808839/11600125-42c2-4ccd-bf3b-f2d2cd91bab8)

**Comment by yuphin** [comment]
Ambient/env. lighting support in other integrators are hit-or-miss atm. Will add them later.
