### ISSUE TITLE
different SPPM, BDPT, Restir GI, Restir PT vs VCM/Path

### ISSUE THREAD

**Issue by tigrazone** [yuphin/Lumen#30]
Hello.
In new bsdf branch I have different result when I change integrator.
VCM
![image](https://github.com/yuphin/Lumen/assets/3808839/e4818688-f3fb-4e4c-85e7-73bcaef19cdc)

Path
![image](https://github.com/yuphin/Lumen/assets/3808839/c00b6065-1683-4045-b2d6-48bc13f1d537)

VCM and Path is almost same.

SPPM, darker
![image](https://github.com/yuphin/Lumen/assets/3808839/3f4a623b-1d16-42eb-a8de-f2d5ff45c4f3)

BDPT is broken
![image](https://github.com/yuphin/Lumen/assets/3808839/9e282820-8b22-4d13-adc4-82844f5b2bf6)

My camera settings for this view is
```
    "camera": {
        "fov": 45,
        "position": [
            -4.404,
            -0.887,
            10.913
        ],
        "dir" : [
            0,0.09, 2
        ]
    },
```

**Comment by tigrazone** [comment]
Restir GI
![image](https://github.com/yuphin/Lumen/assets/3808839/25101c57-3e67-450a-8ff6-ff26fa9b5eab)

Restir PT
![image](https://github.com/yuphin/Lumen/assets/3808839/181ded55-7e71-4e60-8d52-1dfecfe453d3)

**Comment by yuphin** [comment]
BDPT part is fixed. SPPM also supports env. lighting but it's supposed to be biased in the first place. 
ReSTIR GI is not meant to be used with specular reflections. ReSTIR PT should be identical but I've yet to add support and validate for complex BSDFs.

**Comment by tigrazone** [comment]
SPPM goes to black on classroom scene and on torus scene

**Comment by tigrazone** [comment]
"goes to black" maybe is nans. I fix it
