### ISSUE TITLE
glasses not converted well

### ISSUE THREAD

**Issue by tigrazone** [yuphin/Lumen#34]
bedroom scene
![image](https://github.com/yuphin/Lumen/assets/3808839/46012dc5-f922-44ad-b969-2455c24996c0)
this view is
`<matrix value="0.614 -0.057 0.787 -1.470 0.093 0.998 0.070 0.728 -0.789  -0.040   0.613  1.988 0 0 0 1"/>`

with my commit https://github.com/tigrazone/Lumen/commit/a2b4d0c07eefcf59eb5a815822ee60d2d6c5fcbc I have
![image](https://github.com/yuphin/Lumen/assets/3808839/54b25a24-8edd-4b35-b8f1-65346900aaa4)

**Comment by yuphin** [comment]
Should be fixed now. The idea is to make the principled BSDF a default fallback in these cases. So all the dielectric types are assumed to be principled.
