### ISSUE TITLE
what BSDF_FLAG_GLOSSY do?

### ISSUE THREAD

**Issue by tigrazone** [yuphin/Lumen#36]
in previous bsdf implementation GLOSSY was used but in new implementation BSDF_FLAG_GLOSSY used only in 
src\RayTracer\LumenScene.cpp 
but nowhere in shaders.

is it issue?
how to fix it?

**Comment by yuphin** [comment]
Since both 'is_specular()' and 'is_diffuse()' have use cases in shaders, there exists a range of materials in between those 2. So we just call them `Glossy` instead of something like `NotSpecularNorDiffuse`. Plus, it might have some other use cases in the future as well.

**Comment by tigrazone** [comment]
```
// BSDF Props
#define BSDF_FLAG_DIFFUSE 1 << 0
#define BSDF_FLAG_SPECULAR 1 << 1
#define BSDF_FLAG_GLOSSY 1 << 2
#define BSDF_FLAG_REFLECTION 1 << 3
#define BSDF_FLAG_TRANSMISSION 1 << 4
```

i.e. BSDF_FLAG_GLOSSY not used in shaders

**Comment by tigrazone** [comment]
#define BSDF_FLAG_LAMBERTIAN 1 << 5
#define BSDF_FLAG_DISNEY 1 << 6
#define BSDF_FLAG_FROSTBITE 1 << 7
also not used

**Comment by tigrazone** [comment]
is ok to define
#define BSDF_FLAG_GLOSSY BSDF_FLAG_DIFFUSE | BSDF_FLAG_SPECULAR | BSDF_FLAG_REFLECTION
or better
#define BSDF_FLAG_GLOSSY BSDF_FLAG_ALL
?

**Comment by yuphin** [comment]
I've removed those flags. I think it's fine to have a separate glossy flag.
