### ISSUE TITLE
is dielectric material issue?

### ISSUE THREAD

**Issue by tigrazone** [yuphin/Lumen#38]
I try to render scenes\cornell_box\cornell_box_dir.json
![image](https://github.com/yuphin/Lumen/assets/3808839/e9e73adf-543c-4668-8251-ba4b7eebfc12)

when I change glass sphere material to "type": "dielectric" I have different image
![image](https://github.com/yuphin/Lumen/assets/3808839/76f9d583-7101-485d-ae9f-f8da7c4855ee)

i.e. roughness = 0.0

why images are different?

**Comment by tigrazone** [comment]
I try to change
https://github.com/yuphin/Lumen/blob/e08a96350a416de707c5a425ef40a1639e8769f3/scenes/torus/torus.xml#L19
to dielectric
and VCM give me this picture
![image](https://github.com/user-attachments/assets/cd94ec91-460c-4554-9267-690c24d1c871)

with SPPM I have this
![image](https://github.com/user-attachments/assets/da7c5030-b016-4592-ac8d-30bf5957908a)

**Comment by yuphin** [comment]
Yes, I think something in VCM broke while I was adding new materials. 
I'll look into it after I restructure the project a bit and finish up the remaining issues with ReSTIR PT.
