### ISSUE TITLE
doesnt start

### ISSUE THREAD

**Issue by tigrazone** [yuphin/Lumen#39]
Hello.
I built with Visual Studio 2022 and exes show me
![image](https://github.com/user-attachments/assets/3ed67ae5-ea02-40a0-8711-6979ae025f67)

When I run under debugger I see this
![image](https://github.com/user-attachments/assets/3d3b15bc-f68d-4fe0-8134-58491465e8e2)

When I press "Skip" and look at call stack I see 
![image](https://github.com/user-attachments/assets/3df98441-922a-4c0f-af5d-3a8648379049)

I.e. where is no elements with seted index.
I change
https://github.com/yuphin/Lumen/blob/0fbc12756a3118bce1dae47991635727eec6cf8d/src/Framework/VulkanBase.cpp#L22
to
`std::vector<VkFence> _in_flight_fences(MAX_FRAMES_IN_FLIGHT + MAX_FRAMES_IN_FLIGHT);`

and restart I have
![image](https://github.com/user-attachments/assets/8c490df3-06f4-45a7-90d2-697887c2b3c0)
and call stack is
![image](https://github.com/user-attachments/assets/9888ee21-1e0b-42ae-914c-6abd391ffbda)

**Comment by yuphin** [comment]
What does the validation message say?

**Comment by tigrazone** [comment]
now works ok
