### ISSUE TITLE
[Question] about restirgi

### ISSUE THREAD

**Issue by trsh** [yuphin/Lumen#4]
I am lookin at `src\shaders\integrators\restir\gi\temporal_reuse.rgen` and buffer `old_samples`, and I can not understand where its being written. Only accessed at line 97.

**Comment by yuphin** [comment]
Thanks for pointing that out. In the release build it's copied via vkCmdCopyBuffer, see [this line](https://github.com/yuphin/Lumen/blob/f9d73f0ace9997745ea37ea0ca8816991d53ea98/src/RayTracer/ReSTIRGI.cpp#L207). It appears I've forgotten to copy it in the new render graph implementation.

**Comment by yuphin** [comment]
Addressed in ea63f7380fa1d6b75f1792d9802157ad0cbe508c
