### ISSUE TITLE
crash when select ReSTIR PathTracing

### ISSUE THREAD

**Issue by robinzh099314** [yuphin/Lumen#41]
stops in VulkanStructures.h at check(VkResult result, const char* msg = 0)
if (result != VK_SUCCESS && msg)  msg is: 
     Failed to submit draw command buffer

terminal output:
Compiling shader: src/shaders/integrators/restir/gris/ray.rmiss(STREAMING_MODE=0)
Compiling shader: src/shaders/ray.rahit(STREAMING_MODE=0)
Compiling shader: src/shaders/integrators/restir/gris/temporal_reuse.rgen
Compiling shader: src/shaders/ray_shadow.rmiss(STREAMING_MODE=0)
Validation Error: Validation Error: [ UNASSIGNED-Threading-MultipleThreads-Write ] Object 0: handle = 0x27d60e0000000019, type = VK_OBJECT_TYPE_COMMAND_POOL; | MessageID = 0xa05b236e | vkBeginCommandBuffer():  THREADING ERROR : object of type VkCommandPool is simultaneously used in current thread 21756 and thread 37988

Environment:
Windows11Pro 22H2
VisualStudio 2022
Vulkan 1.3.290.0
CMake 3.30.2

**Comment by yuphin** [comment]
The issue should be fixed now, thanks for raising.
