### ISSUE TITLE
How do I load complex scenes?

### ISSUE THREAD

**Issue by ohmaya** [yuphin/Lumen#9]
I can load some scenes, for example:
Lumen.exe scenes/occluded2.json

I can't load (the Tungsten file):
Lumen.exe scenes/bedroom/scene.json

Thanks.

**Comment by ohmaya** [comment]
I still can't load bedroom.

**Comment by yuphin** [comment]
Have you tried the loading the `scenes/bedroom/scene.xml` file that's in the repo? Currently only Mitsuba files (xml)  are supported. JSON files in the other scenes use Lumen's own format and not Tungsten's.

**Comment by ohmaya** [comment]
It works, thank you.
